# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# FIXME
# This is a very basic config!
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      # - id: forbid-new-submodules
      # - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      # - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
        - id: black
          args: ["-l 120"]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
        - id: blacken-docs